version: '3.7'
services:

  &db-host db:
    image: postgres:11.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: &db-password root
      POSTGRES_USER: &db-user root
      POSTGRES_DB: &db-db database

  &redis-host redis:
    image: redis:5.0.7-alpine

  &app-host app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      DB_HOST: *db-host
      DB_USERNAME: *db-user
      DB_PASSWORD: *db-password
      DB_DATABASE: *db-db
      APP_URL: "localhost"
      REDIS_HOST: *redis-host
      REDIS_PASSWORD: null
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
    volumes:
      - ./src/app:/app